# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.1-node-browsers

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      # prepare the database
      - run: touch tuctvc_create.sql

  deployment:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: scp -P 65002 -r * u436461244@5.181.218.1:~/domains/tuctvc.com/public_html/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deployment:
          requires:
            - build